name: Snowflake Query in Demo Env

on:
  workflow_dispatch:

jobs:
  run-snowflake-query:
    runs-on: ubuntu-latest

    steps:
    - name: Install snowflake-cli
      uses: Snowflake-Labs/snowflake-cli-action@v1.5
      with:
        cli-version: "latest"
        default-config-file-path: ".snowflake/config.toml"

    - name: Add SnowSQL to PATH
      run: echo "$HOME/.snowsql" >> $GITHUB_PATH

    - name: Run SQL Query on Snowflake (Demo)
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.DEMO_SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.DEMO_SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.DEMO_SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ROLE: ${{ secrets.DEMO_SNOWFLAKE_ROLE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.DEMO_SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.DEMO_SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.DEMO_SNOWFLAKE_SCHEMA }}
      run: |
        ~/.snowsql/snowsql -a $SNOWFLAKE_ACCOUNT \
          -u $SNOWFLAKE_USER \
          -p $SNOWFLAKE_PASSWORD \
          -r $SNOWFLAKE_ROLE \
          -w $SNOWFLAKE_WAREHOUSE \
          -d $SNOWFLAKE_DATABASE \
          -s $SNOWFLAKE_SCHEMA \
          -q "CREATE OR REPLACE TABLE demo_employees (
                id INT,
                name STRING,
                role STRING,
                start_date DATE,
                salary NUMBER(10,2)
              );"
