name: Snowflake Query in Demo Env

on:
  workflow_dispatch:

jobs:
  run-snowflake-query:
    runs-on: ubuntu-latest
    environment: Demo  

    steps:
    - name: Install Snowflake CLI manually via pip
      run: |
        python3 -m pip install --upgrade snowflake-cli



    # - name: Add sf CLI to PATH
    #   run: echo "${{ steps.install_sf.outputs.install-dir }}" >> $GITHUB_PATH

    - name: Set up Snowflake config.toml
      run: |
        mkdir -p .snowflake
        cat > .snowflake/config.toml <<EOF
        [connections.demo]
        account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
        username = "${{ secrets.SNOWFLAKE_USER }}"
        password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
        role = "${{ secrets.SNOWFLAKE_ROLE }}"
        warehouse = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
        database = "${{ secrets.SNOWFLAKE_DATABASE }}"
        schema = "${{ secrets.SNOWFLAKE_SCHEMA }}"
        EOF

    - name: Confirm sf is in PATH
      run: which sf || echo "sf command NOT found in PATH"

    - name: Run SQL query using Snowflake CLI (try with sf)
      run: |
        sf -c demo query "CREATE OR REPLACE TABLE demo_employees (
          id INT,
          name STRING,
          role STRING,
          start_date DATE,
          salary NUMBER(10,2)
        );"
      
