name: Snowflake Query in Demo Env

on:
  workflow_dispatch:

jobs:
  run-snowflake-query:
    runs-on: ubuntu-latest
    environment: Demo

    steps:
    - name: Install Snowflake CLI
      id: install_sf
      uses: Snowflake-Labs/snowflake-cli-action@v1.5
      with:
        cli-version: "latest"
        default-config-file-path: ".snowflake/config.toml"

    - name: Set up Snowflake config.toml
      run: |
        mkdir -p .snowflake
        cat > .snowflake/config.toml <<EOF
        [connections.demo]
        account = "${{ secrets.DEMO_SNOWFLAKE_ACCOUNT }}"
        username = "${{ secrets.DEMO_SNOWFLAKE_USER }}"
        password = "${{ secrets.DEMO_SNOWFLAKE_PASSWORD }}"
        role = "${{ secrets.DEMO_SNOWFLAKE_ROLE }}"
        warehouse = "${{ secrets.DEMO_SNOWFLAKE_WAREHOUSE }}"
        database = "${{ secrets.DEMO_SNOWFLAKE_DATABASE }}"
        schema = "${{ secrets.DEMO_SNOWFLAKE_SCHEMA }}"
        EOF

    - name: Debug Show install path
      run: | 
        echo "Installed at: ${{ steps.install_sf.outputs.install-dir }}"



    - name: Run SQL query using Snowflake CLI
      run: |
        "${{ steps.install_sf.outputs.install-dir }}/sf" -c demo query "CREATE OR REPLACE TABLE demo_employees (
          id INT,
          name STRING,
          role STRING,
          start_date DATE,
          salary NUMBER(10,2)
        );"
