name: Snowflake Query in Demo Env

on:
  workflow_dispatch:

jobs:
  run-snowflake-query:
    runs-on: ubuntu-latest
    environment: Demo

    steps:
    - name: Install Snowflake CLI using pipx
      run: |
        pipx install snowflake-cli
        echo "/opt/pipx_bin" >> $GITHUB_PATH

    - name: Create Snowflake config at ~/.snowflake/config.toml
      run: |
        mkdir -p ~/.snowflake
        cat > ~/.snowflake/config.toml <<EOF
        [connections.demo]
        [connections.my_example_connection]
        account = "RHMDJPI-XY35622"
        user = "SANDEEP39642"
        password = "Welcome@23071995"
        role = "ACCOUNTADMIN"
        warehouse = "SNOWFLAKE_LEARNING_WH"
        database = "SNOWFLAKE_LEARNING_DB"
        schema = "SNOWFLAKEDEMOSCHEMA"
        EOF
           chmod 600 ~/.snowflake/config.toml


    - name: Run SQL using Snowflake CLI
      run: |
        snow sql --connection demo --query "CREATE OR REPLACE TABLE demo_employees (
          id INT,
          name STRING,
          role STRING,
          start_date DATE,
          salary NUMBER(10,2)
        );"

    - name: Run SQL File
      run: |
        snow sql --connection demo --file scripts/init_table.sql
