name: Snowflake Query in Demo Env

on:
  workflow_dispatch:

jobs:
  run-snowflake-query:
    runs-on: ubuntu-latest
    environment: Demo  

    steps:
    - name: Install Snowflake CLI using Action
      id: install_sf
      uses: Snowflake-Labs/snowflake-cli-action@v1.5
      with:
        cli-version: "latest"
        default-config-file-path: ".snowflake/config.toml"
        
    - name: Add pipx binaries to PATH
      run: |
        echo "/opt/pipx_bin/snow_pipx_path" >> $GITHUB_PATH

    - name: Verify sf CLI is installed and on PATH
      run: |
        which sf
        sf --version


    # - name: Check Snowflake CLI version
    #   run: sf --version




    # - name: Add sf CLI to PATH
    #   run: echo "${{ steps.install_sf.outputs.install-dir }}" >> $GITHUB_PATH

    - name: Set up Snowflake config.toml
      run: |
        mkdir -p .snowflake
        cat > .snowflake/config.toml <<EOF
        [connections.demo]
        account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
        username = "${{ secrets.SNOWFLAKE_USER }}"
        password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
        role = "${{ secrets.SNOWFLAKE_ROLE }}"
        warehouse = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
        database = "${{ secrets.SNOWFLAKE_DATABASE }}"
        schema = "${{ secrets.SNOWFLAKE_SCHEMA }}"
        EOF

   

    - name: Run SQL query using Snowflake CLI (try with sf)
      run: |
        sf -c demo query "CREATE OR REPLACE TABLE demo_employees (
          id INT,
          name STRING,
          role STRING,
          start_date DATE,
          salary NUMBER(10,2)
        );"
      
